server:
  port: 8008

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microservicio01
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/customers/**
        - id: microservicio02
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/accounts/**
        - id: microservicio03
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/credits/**
        - id: microservicio04
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/transacctions/**
