
application:
  endpoints:
    url: http://localhost:8081/api/
server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb+srv://nttdatauser:s2D4xMuLPx5zMj0f@dbbootcamp57.0qsps.mongodb.net/?retryWrites=true&w=majority&appName=dbbootcamp57
      database: Bootcamp57
  application:
    name: microservicio02

eureka:
  serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  prefer-ip-address: true